### PR TITLE
Partial implementation of API get route handlers

### PR DESCRIPTION
**Pull request by cmoralespv**
General Setup
- Created tentative folder structure
- Installed node-postegres
- Configured and connected to postgres server
- Configured express.routes middleware for get and post routes

Implemented API GET request for List Reviews
- Initially built it using error first callback pattern
- Refactored to promise-based
- Tested connection using postman
- Tested connection to database
- Getting data, not yet manipulating it

Implemented API GET request for Metadata
- Tested connection using postman
- Tested connection to database
- Getting partial data, not yet manipulating it

### CODE REVIEW

**Comment by cmoralespv** [comment]
[Install an applications to interface with PostgresSQL database](https://trello.com/c/KMJEFlMH/23-install-an-applications-to-interface-with-postgressql-database)

**Comment by cmoralespv** [comment]
[Implement List Reviews](https://trello.com/c/fz5E9LOJ/25-implement-list-reviews)

**Comment by cmoralespv** [comment]
[Implement Get Review Metadata](https://trello.com/c/TbBAfgIe/26-implement-get-review-metadata)

**Comment by jnbooth** [comment]
We climbed this whole mountain. 5TRON6

**Pull request merged**
